<?php
require('base/controller.php');
require('base/layout.php');
require('base/record.php');
require('base/acl.php');
require('base/auth.php');
require('base/param.php');
require('base/table.php');
require('base/validator.php');
require('base/tools.php');
?>
